// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA4V9kR8gnltCIa_pv2VJegwlVf13aXfpA",
      authDomain: "vendido-new-aa289.firebaseapp.com",
      databaseURL: "https://vendido-new-aa289-default-rtdb.asia-southeast1.firebasedatabase.app",
      projectId: "vendido-new-aa289",
      storageBucket: "vendido-new-aa289.appspot.com",
      messagingSenderId: "440607219193",
      appId: "1:440607219193:web:1b1eced5de709692917128",
      measurementId: "G-4R726BW55W"
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MBzs7_lEj-0ysHQyXNWVpq8O_Xzfe6c',
    appId: '1:440607219193:android:db17de7a24f41361917128',
    messagingSenderId: '440607219193',
    projectId: 'vendido-new-aa289',
    databaseURL: 'https://vendido-new-aa289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendido-new-aa289.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbw4Jctmr8f88VqS6K8LFqWqfcDvlmFk',
    appId: '1:440607219193:ios:9dbe22ab30579e5c917128',
    messagingSenderId: '440607219193',
    projectId: 'vendido-new-aa289',
    databaseURL: 'https://vendido-new-aa289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendido-new-aa289.appspot.com',
    androidClientId:
    '440607219193-7m4itigl4ddls834ho8gbv158h3hieoc.apps.googleusercontent.com',
    iosClientId:
    '440607219193-dhep8pdpa35qkmaiiatb2d79p8chgvvv.apps.googleusercontent.com',
    iosBundleId: 'vendido-new-aa289.appspot.com',
  );
}
